# Generated by Django 2.2.15 on 2021-10-27 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('vehicleNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicleStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicleGroup', model_utils.fields.StatusField(choices=[('DMG', 'DMG'), ('Stockyard', 'Stockyard')], default='DMG', max_length=100, no_check_for_status=True)),
                ('totalPermits', models.IntegerField(default=0, null=True)),
                ('ownerPhone', models.CharField(blank=True, max_length=30, null=True)),
                ('licenseStart', models.DateTimeField(blank=True, null=True)),
                ('licenseEnd', models.DateTimeField(blank=True, null=True)),
                ('licenseStatus', models.CharField(max_length=30, null=True)),
                ('capacity', models.FloatField(default=0, null=True)),
                ('vehicleType', model_utils.fields.StatusField(choices=[('Tipper', 'Tipper'), ('Tractor', 'Tractor'), ('Lorry', 'Lorry')], default='Tipper', max_length=100, no_check_for_status=True)),
                ('gpsIMEI', models.IntegerField(null=True)),
                ('telecomProvider', models.CharField(max_length=30, null=True)),
                ('simNo', models.CharField(blank=True, max_length=30, null=True)),
                ('registrationDate', models.DateField(auto_now_add=True, null=True)),
                ('installationtype', model_utils.fields.StatusField(choices=[('New Installation', 'New Installation'), ('Migration', 'Migration'), ('Renewal with existing hardware', 'Renewal with existing hardware')], default='New Installation', max_length=100, no_check_for_status=True)),
                ('registrationBy', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='PermitTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('PermitNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('ILMS_number', models.CharField(blank=True, max_length=30, null=True)),
                ('PermitStart', models.DateTimeField(blank=True, null=True)),
                ('PermitValidTill', models.DateTimeField(blank=True, null=True)),
                ('LoadingLocation', models.CharField(blank=True, max_length=30, null=True)),
                ('Destination', models.CharField(blank=True, max_length=30, null=True)),
                ('Qty', models.FloatField(blank=True, default=0, null=True)),
                ('Alerts', models.IntegerField(blank=True, default=0, null=True)),
                ('VehicleNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permit_vehicles', to='transport.Vehicle')),
            ],
            options={
                'verbose_name': 'Permit Tracker',
                'verbose_name_plural': 'Permits Tracker',
            },
        ),
    ]
